apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: {{ .Values.ingressClassName }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.hostName }}
        - {{ .Values.frontendHostName }}
      secretName: lti-tls-secret

  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.image.api.port }}
    - host: {{ .Values.frontendHostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.image.frontend.port }}
