apiVersion: v1
kind: Service
metadata:
  name: etl
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: etl
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.image.etl.port }}