clientId: 104410000000000150
authenticateLoginUrl: https://uvadlo-dev.instructure.com/api/lti/authorize_redirect
authenticateTokenUrl: https://canvas.iguideme.com/login/oauth2/token
canvasUrl: canvas.instructure.com
jwksUrl: https://canvas.instructure.com/api/lti/security/jwks
jwtSecretKey: change_this_secret
deploymentIds: 1:8865aa05b4b79b64a91a86042e43af5ea8ae79eb
apiKey: a_super_secure_secret
apiKeyName: X-API-Key
apiUrl: https://iguideme.local:8433
frontendUrl: http://iguideme.local:2000
hostName: iguideme.local
ingressClassName: nginx

# One of azure, kubernetes
secretProvider: kubernetes

image:
  api:
    repository: ghcr.io/iguideme/api
    tag: latest
    pullPolicy: Always
    port: 8000
  frontend:
    repository: ghcr.io/iguideme/frontend
    tag: latest
    pullPolicy: Always
    port: 3000
  nginx:
    repository: nginx
    tag: latest

postgres:
  image: postgres:15
  volumeSize: 1Gi
  env:
    DB_HOST: postgres
    POSTGRES_USER: iguideme
    POSTGRES_PASSWORD: thispasswordisridiculous
    POSTGRES_DB: iguideme-main-pod

ingress-nginx:
  controller:
    service:
      ports:
        http: 8080
      targetPorts:
        http: http

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: iguideme-canvas-token
      key: CANVAS_API_KEY
      envVar: CANVAS_API_KEY
    - name: iguideme-lti-key
      key: LtiKey
      envVar: CLIENT_ID
    - name: iguideme-jwt-key
      key: LTI__SigningKey
      envVar: JWT_SECRET_KEY